# Generated by Django 2.0.1 on 2018-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assigns_due',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='help_resources',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='objs',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reading',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
