# Generated by Django 2.0.1 on 2018-04-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180412_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfile',
            name='lesson_being_used',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Lesson'),
            preserve_default=False,
        ),
    ]
