# Generated by Django 2.0.1 on 2018-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_classfile_lesson_being_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
