# Generated by Django 2.0.1 on 2018-04-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180422_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfile',
            name='link',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='classfile',
            name='title',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
