# Generated by Django 2.0.1 on 2018-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180422_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfile',
            name='some_file',
            field=models.FileField(default='-', upload_to='documents/'),
        ),
    ]
