# Generated by Django 2.0.1 on 2018-04-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_classfile_some_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfile',
            name='some_file',
        ),
    ]
